server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    reigster-with-eureka: true
    fetch-register: true
    service-url:
      #      defaultZone: http://localhost:7101/eureka # 单机版
      defaultZone: http://eureka7001.com:7101/eureka,http://eureka7002.com:7102/eureka  #集群版