server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: payment_route
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**

        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true,
      fetch-register: true,
      defaultZone: http://eureka7001.com:7101/eureka